### ISSUE TITLE
Move assemblyscript to dependencies

### ISSUE THREAD

**Issue by chadoh** [near/near-sdk-as#106]
Assertions:

* **Projects don't need it**: Having both `near-sdk-as` and `assemblyscript` as separate dependencies in a project provides flexibility that, for most projects, is a hassle without any benefit
* **`near-sdk-as` suffers**: Updating `near-sdks-as` in a way that gives projects this flexibility adds complexity and slows down its evolution

## Projects don't need it

Right now, many NEAR apps have separate dependabot-created PRs to update `near-sdk-as` & `assemblyscript`. The `assemblyscript` update came first, and introduced bugs (https://github.com/near-examples/guest-book/pull/133) unless the project waits for a subsequent `near-sdk-as` update and uses it first.

I can think of a couple situations where projects would want to have a version of `assemblyscript` that mismatches the one used in `near-sdk-as`:

1. One contract written with `near-sdk-as`, another written with raw `assemblyscript` for performance reasons
2. A contract written with `near-sdk-as`, and some other aspect of the project (such as the frontend) built with `assemblyscript`

In both situations, if `near-sdk-as` came packaged with its own version of `assemblyscript` that mismatched what the project needed elsewhere, the project could easily work around that by using [yarn workspaces](https://classic.yarnpkg.com/en/docs/workspaces/), [lerna](https://github.com/lerna/lerna), or [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules). 

My guess is that most existing projects that use `near-sdk-as` are not including `assemblyscript` for any other reason. If that's true (how can we test this assumption?), then an upgrade to `near-sdk-as` that requires removing `assemblyscript` from `package.json` would be a simple and welcome breaking change.

## `near-sdk-as` suffers

As mentioned in https://github.com/near-examples/guest-book/pull/133#issuecomment-637619401, we could add `assemblyscript` to `peerDependencies` for `near-sdk-as`. This would be a great way to give projects the flexibility to update `assemblyscript` at a different rate than they update `near-sdk-as`.

However, it comes with costs. `near-sdk-as` would need to make sure changes are backwards-compatible for several versions of `assemblyscript`. This complicates the code, and means that it takes longer to offer new, powerful features of `assemblyscript`, such as [interfaces and abstract methods](https://github.com/AssemblyScript/assemblyscript/releases/tag/v0.10.0).

If it's true that most projects do not need this flexibility, then this slower evolution comes with no upside.

**Comment by chadoh** [comment]
@vgrichina I'm curious if you agree with my arguments above, and if you think it's worth testing my first assumption.

**Comment by vgrichina** [comment]
@chadoh @willemneal I agree that it makes sense to just bring assemblyscript with near-sdk-as given that these are relatively tightly coupled (because of custom code transforms at least).

> In both situations, if near-sdk-as came packaged with its own version of assemblyscript that mismatched what the project needed elsewhere, the project could easily work around that by using yarn workspaces, lerna, or git submodules.

hmm, not sure why would you need special tool. You can have multiple conflicting versions of packages in single project using plain npm. You would just need to avoid calling assemblyscript through `near-sdk-as` when compiling if you want to use other version.
