### ISSUE TITLE
isValidAccountID does not exist on typeof env

### ISSUE THREAD

**Issue by ALuhning** [near/near-sdk-as#212]
After importing env from 'near-sdk-as', I'm unable to access isValidAccountID - VS Code says it does not exist on typeof env.

Is the function missing the decorators (notice everything else in the file has them):
//@ts-ignore
  @inline

**Comment by willemneal** [comment]
Hmm, well the other functions in that file call globals declared in another file.  This way only the functions that are used will trigger the import required.  Thus there are inlined as to ensure that there is no indirection when compiled.  However, other functions should be inlined only if the optimizer wants it to be.

Can you post your current setup?  Are you using version 1.0.0?

**Comment by ALuhning** [comment]
I am using near-sdk-as ver 1.0.1.

import { Context, u128, env } from 'near-sdk-as'

and in an function I'm trying to do:
assert(env.isValidAccountID(escrow_account_id), ERR_INVALID_ACCOUNT_ID)

**Comment by willemneal** [comment]
Hmm, one thing to try when VSCode is made about codes is to restart the TS lang server, F1 and then type `restart typescript`.

Are you able to compile the file outside of VSCode?  If not, what compile errors are you getting?

**Comment by ALuhning** [comment]
restarting the typescript server didn't fix it; however, it does compile and js file created doesn't seem to have any issue finding it - must be a VS Code issue.  Thanks.

**Comment by ALuhning** [comment]
I spoke too soon - not sure what I was doing earlier when I check the compilation, but it is failing with following error code:

ERROR TS2339: Property 'isValidAccountID' does not exist on type '~lib/near-sdk-as/sdk/env/env/env'.

   assert(env.isValidAccountID(new_owner_id), ERR_INVALID_ACCOUNT_ID);
              ~~~~~~~~~~~~~~~~
 in assembly/main.ts(73,14)

**Comment by willemneal** [comment]
Is it possible to share the project? If not, can you inspect `node_modules/near-sdks-as/assembly/sdk/env/env.ts` for the function?

**Comment by ALuhning** [comment]
The function isn't in that env.ts file.  I just blew away the node_modules folder and cache and reinstalled and rechecked to see if it would show up - still not there.  Yes, package number says 1.0.1.  Also did a npm list near-sdk-as to confirm 1.0.1 is being used.

Pushed it all to a repository (incl node_modules) - https://github.com/ALuhning/VPC-FT

**Comment by willemneal** [comment]
Ah I forgot to publish after the `isValidAccountID` update.  If you update to `v1.1.0`, it should be there.

**Comment by ALuhning** [comment]
Yes it is.  Thank you very much.
