### ISSUE TITLE
storage.set - i32 can't be converted to u8

### ISSUE THREAD

**Issue by ALuhning** [near/near-sdk-as#217]
Have tried storage.set<u8>('precision', precision) where precision passed in is typed as u8.  Get an error during compile saying i32 can't be converted to u8.  

I know I can import u128 from near-sdk-as and use that, but seems like overkill for a small positive number.  

Get same compiler error with u16.

Peter | Near Protocol thinks I've run into an issue that storage.set doesn't support "small integer* types" from AssemblyScript - asked me to submit this issue.

**Comment by willemneal** [comment]
Ah yeah you need to use `store.setPrimitive<u8>` and `getPrimitive<u8>`. The issue is that primitives cannot equal null since `null` is a runtime value of 0, or the 0th index into the function table reserved for null.
