### ISSUE TITLE
Disable storage_iter*

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/near-sdk-as#4]
We should remove `storage_iter*` usage from SDK.
Storage iterators makes it expensive and restricts underlying data structure on the Node side to be sorted tree. We should be able to achieve TPS increase, by replacing underlying storage with key-value hash-based storage in the future, which will make storage access much cheaper.

See https://github.com/nearprotocol/nearcore/issues/2234 for background

**Comment by willemneal** [comment]
closed by #7
