### ISSUE TITLE
Error calling validator_stake from contract

### ISSUE THREAD

**Issue by Em-kale** [near/near-sdk-as#409]
Unexpected error from validator_stake method in env.ts on build: Type ArrayBuffer cannot be converted to type 'u64' - in line 337 of near-sdk-core/env/env.ts

**To Reproduce**

1. Write function within contract which calls env.validator_stake(account_id: string), passing in a string
2. Attempt to build 

**Expected behavior**
Should return stake as type u128

Version:
near-sdk-as: 2.2.4

**Comment by mehtaphysical** [comment]
Duplicate of #436 i think
