### ISSUE TITLE
Error in env.validator_stake(accountName)

### ISSUE THREAD

**Issue by theophoric** [near/near-sdk-as#436]
**Describe the bug**
There appears to be an error in `env/env.ts#validator_stake(accountId:string)` that causes a compile-time error.

**To Reproduce**
Compile the following code with `asb`:

```ts
import {env, logging, context} from 'near-sdk-as';

export function foo():void {
  logging.log(env.validator_stake("something.near"));
}
```

The observed output is:

```sh
> sandbox@0.0.1 build:env_test
> asb assembly/env_test.ts

ERROR AS202: Type '~lib/arraybuffer/ArrayBuffer' cannot be changed to type 'u64'.

     let id_ptr = changetype<u64>(id);
                  ~~~~~~~~~~~~~~~~~~~
 in ~lib/near-sdk-core/env/env.ts(337,18)

```

**Expected behavior**
It compiles.

**Screenshots**
Issue appears to be with the unsafe`changetype<u64>`
```ts
export function validator_stake(account_id: string): u128 {
    let data = new Uint8Array(sizeof<u128>());
    let id = String.UTF8.encode(account_id);
    let id_ptr = changetype<u64>(id);
    _validator_stake(id.byteLength, id_ptr, data.dataStart);
    return u128.from(data);
  }
```

**Desktop (please complete the following information):**
 - OS: osx 11.1
 - Version: near-sdk-as 2.2.0

**Comment by mehtaphysical** [comment]
Added a PR that maybe will fix this? Seems some of the typing was just a bit off.
