### ISSUE TITLE
Exporting functions from submodules

### ISSUE THREAD

**Issue by gagdiez** [near/near-sdk-as#491]
Right now, there is no simple way to export a function that was imported from a submodule. This makes it hard to modularize an assembly contract, therefore complicating the whole developing process. 

I would love if we could have the option to make:

> import {f1, f2, f3 ... fn} from './bar'} 
> export {f1, f2, f3 ... fn}

**Comment by alsakhaev** [comment]
I also find this feature useful. Was surprised when I could not call a function imported this way
