### ISSUE TITLE
Unexpected transfer amount - ContractPromiseBatch

### ISSUE THREAD

**Issue by ALuhning** [near/near-sdk-as#550]
**Describe the bug**
When using ContractPromiseBatch to transfer funds from the contract account to another account, the transfer amount does unexpected things.

**To Reproduce**
I'm trying to transfer 3 NEAR.  The amount variable in function below = 3.  I have tried several hardcode iterations with comments indicating what the results are.  I cannot figure out how to get the transfer function to send 3 NEAR instead of 3 yocto.

`// transfer from user account to contract account (integer)
function _nearTransferInteger(amount: u64, account: AccountId): bool {
 //let newAmount = u128.from(3000000000000000000000000) - works but transfers 6011292615620689920 yocto

 //let newAmount = u128.from(3) - works but transfers 3 yocto

 //let newAmount = new u128(3) - works but transfers 3 yocto

 //let newAmount = new u128(3000000000000000000000000) - works but transfers 6011292615620689920 yocto

 //let newAmount: u128 = u128.from('3') - works but transfers 3 yocto

 //let newAmount = u128.from('3000000000000000000000000') - does not work, exceeds account balance

 //let stringAmount = amount.toString()

 //let newAmount = u128.from(stringAmount) - works but transfers 3 yocto

  let promise = ContractPromiseBatch.create(account)
  .transfer(newAmount)
  return true
}`

**Expected behavior**
I expect it to transfer 3 NEAR if I give the transfer call a u128.from(3)

**Comment by mehtaphysical** [comment]
I was able to transfer 3 NEAR with this code:

```ts
import { ContractPromiseBatch, u128 } from "near-sdk-as";

export function transfer(): void {
  ContractPromiseBatch.create('someaccount.testnet').transfer(
    u128.from('3000000000000000000000000')
  );
}
```

https://explorer.testnet.near.org/transactions/E8dFchFFGVXF8BRmVVhpTq6oggVoLaiqMhCWWa8PPPpZ.

I think you'll need to do `u128.from('3000000000000000000000000')` instead of `u128.from(3000000000000000000000000)` because `3000000000000000000000000` is so large.

Can you send an explorer link to the transaction that failed when you did `u128.from('3000000000000000000000000')`?

**Comment by ALuhning** [comment]
Here's one - just tried it again - https://explorer.testnet.near.org/transactions/7goR9gXXWDJbQpCeGeskz1LBMnv3FYmAwp53zp9jbTE2

only difference is that instead of putting it right into the transfer, I do:
 let newAmount = u128.from('3000000000000000000000000')
  let promise = ContractPromiseBatch.create(account)
  .transfer(newAmount)

**Comment by ALuhning** [comment]
I feel a little silly - just realized I'm trying to do the transfer from the wrong contract account and one that doesn't actually have enough balance - so believe everything is probably working correctly.  Will test and close this if so.

**Comment by ALuhning** [comment]
Solved - as per last comment.  Was my issue, not an issue with the SDK.  Thanks for the help.
