### ISSUE TITLE
 `yarn doc`  cannot build doc

### ISSUE THREAD

**Issue by yjhmelody** [near/near-sdk-as#552]
```
 Error: Tried to set an option (ignoreCompilerErrors) that was not declared.
 Error: Tried to set an option (stripInternal) that was not declared.
 Error: Tried to set an option (inputFiles) that was not declared.
 error Command failed with exit code 1.
 ```

**Comment by willemneal** [comment]
After looking into this it seems that the update to the newer version of `typedoc` is the reason for these errors.  However, after updating the `tsconfig.json`, it can no longer ignore the errors produced by `tsc`. 

I can't seem to ignore files in `node_modules/`, which contains a code which typescript does not like. 

Rolling back `typedoc` to the last minor version didn't work with `typescript` >= 4.x.

So it seems that the way to fix this is to roll back both `tsc` and `typedoc`, but this doesn't seem the correct thing to do.
