### ISSUE TITLE
Improve error handling in VM Runner runtime

### ISSUE THREAD

**Issue by willemneal** [near/near-sdk-as#58]
Currently if an account is not present in a call, the error says:

>Error: Failed to run successfully: ,,thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', runtime/near-vm-runner-standalone/src/main.rs:211:9

This is not clear that the problem is the missing account.

**Comment by janedegtiareva** [comment]
This is obsolete.
