### ISSUE TITLE
What is the right way to panic or throw Error ?

### ISSUE THREAD

**Issue by nativeanish** [near/near-sdk-as#709]
I looked up in near-sdk-as where I found env.panic() method which invokes or create a panic on near VM. So I have two code
`throw new Error("Error raise");`
and there is another code 
`
logging.log("Error raise");
env.panic();
`
which one is right and ethical way to panic ?

**Comment by willemneal** [comment]
There is no unethical way to error.  But in the second one is not recommended because you are logging your error instead of returning an error string with the failure.  You can also use `assert(.., "message")`, which is the most common way.
