### ISSUE TITLE
Confusing error handling in case deserialization fails

### ISSUE THREAD

**Issue by vgrichina** [near/near-sdk-as#90]
Check out https://gitpod.io#snapshot/3e532bf8-bf84-4cc4-86f3-016667bc11b1

Looks like in earlier version of project above `premium` was boolean, so when it was serialized like that and then later deserialized with current code it resulted in `BadUtf16` error (see attached)

![2020-05-19 14 33 19](https://user-images.githubusercontent.com/126710/82380676-b9aa7680-99dd-11ea-8fa3-091dd5bc4a11.jpg)

Ideally we should give more clear error indicating what went wrong. Smth like `Expected decimal string when deserializing 'ModelObject.premium', but got 'false'`.

**Comment by willemneal** [comment]
How do you trigger the error?  I've tried it twice and t works for me.  Not that we shouldn't improve error handling.

Here is what is generated for `PostedMessage`
```ts
export class PostedMessage {
  premium: u128;
  sender: string;
  constructor(public text: string) {
    this.premium = context.attachedDeposit;
    this.sender = context.sender;
  }

  decode<_V = Uint8Array>(buf: _V): PostedMessage {
    let json: JSON.Obj;
    if (buf instanceof Uint8Array) {
      json = JSON.parse(buf);
    } else {
      assert(buf instanceof JSON.Obj, "argument must be Uint8Array or Json Object");
      json = <JSON.Obj> buf;
    }
    return this._decode(json);
  }

  static decode(buf: Uint8Array): PostedMessage {
    return decode<PostedMessage>(buf);
  }

  private _decode(obj: JSON.Obj): PostedMessage {
    this.premium = obj.has("premium") ? decode<u128, JSON.Obj>(obj, "premium"): this.premium;
    this.sender = obj.has("sender") ? decode<string, JSON.Obj>(obj, "sender"): this.sender;
    this.text = obj.has("text") ? decode<string, JSON.Obj>(obj, "text"): this.text;
    return this;
  }

  _encode(name: string | null = "", _encoder: JSONEncoder | null = null): JSONEncoder {
    let encoder = _encoder == null ? new JSONEncoder() : _encoder;
    encoder.pushObject(name);
    encode<u128, JSONEncoder>(this.premium, "premium", encoder);
    encode<string, JSONEncoder>(this.sender, "sender", encoder);
    encode<string, JSONEncoder>(this.text, "text", encoder);
    encoder.popObject();
    return encoder;
  }
  encode(): Uint8Array {
    return this._encode().serialize();
  }

  serialize(): Uint8Array {
    return this.encode();
  }

  toJSON(): string {
    return this._encode().toString();
  }
}
```

**Comment by vgrichina** [comment]
@willemneal here's easier repro:
https://gitpod.io#snapshot/a7e3ca41-45c5-4087-af3d-f91e5c0d68f5

Should just always be triggering error because of:
```
  decode<PostedMessage>(encode<OldMessage>(new OldMessage('text')));
```

**Comment by janedegtiareva** [comment]
This might be happening because of a misspelling of a parameter.

**Comment by janedegtiareva** [comment]
@amgando volunteered to confirm whether this is due to parameters.

**Comment by amgando** [comment]
definitely seeing the error in JS console at the Gitpod link that @vgrichina posted above

1. open the link
2. login
3. submit a premium message
4. open JS developer console in browser to see error:

![image](https://user-images.githubusercontent.com/24913/82940306-4be1ea00-9f9d-11ea-95be-3031c82e2584.png)

**Comment by amgando** [comment]
@willemneal not sure where to go from here to fix but would be interested in pairing if you've got the time

**Comment by vgrichina** [comment]
> This might be happening because of a misspelling of a parameter.

I think it can happen for variety of serialization problems, in my repro it’s being different type of argument. 

My working theory is that BadUtf16 is actually happening when we are trying to return more specific error string (I saw it happening before with either assert or panic).

**Comment by vgrichina** [comment]
Why is this p3? Sound pretty bad DevX issue, I'd say it's P1.

It's very hard for newcomer to figure out what is going on.

**Comment by vgrichina** [comment]
Re-opening this as still seems to be an issue:
https://app.slack.com/client/TCDLTDN5D/CTUMAR344/thread/CTUMAR344-1594073023.281400

**Comment by janedegtiareva** [comment]
Picking this up to pair on as part of knowledge transfer effort with @willemneal.

**Comment by janedegtiareva** [comment]
https://github.com/near/near-sdk-as/pull/146#pullrequestreview-445147114
