### ISSUE TITLE
should as-pect test Context conditionally set signer and predecessor?

### ISSUE THREAD

**Issue by amgando** [near/near-sdk-as#93]
`predecessor` sounds like `sender-1`  (but it’s actually `sender - n` where `n` is cross-contract hops)

so `predecessor` on a single contract call could just be set to `sender`, so they would be the same in `as-pect` tests using `Context`

if this doesn't make sense let's close the issue @chadoh

**Comment by janedegtiareva** [comment]
Confusion point: in a sequence of chained promise calls, what is the difference of predecessor vs sender? 

Sender is whoever signed the original txn. It should stay consistent throughout the chain of cross-contract calls. 
Predecessor is whoever called this particular function.
