### ISSUE TITLE
PersistentMap is not iterable

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-sdk-as#96]
Currently there is no way to iterate over `PersistentMap` whereas the implementation in Rust supports iteration https://github.com/near/near-sdk-rs/blob/139803224fca5a3f6178a31fa2202ba013ed0ec7/near-sdk/src/collections/map.rs#L222.

**Comment by janedegtiareva** [comment]
* PR in progress https://github.com/near/near-sdk-as/pull/85

**Comment by janedegtiareva** [comment]
AC: feature parity with rust. APIs should match.

**Comment by potatodepaulo** [comment]
@willemneal is this done or in progress?

**Comment by janedegtiareva** [comment]
User feedback snippet from Zod 
**6. PersistentMap is missing iteration (saw there is an issue for it)**
